api:
  insecure: true
  dashboard: true
  debug: true

log:
  level: DEBUG

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yml"
