services:
  agent:
    image: portainer/agent
    depends_on:
      - portainer
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    networks:
      - portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

  portainer:
    image: portainer/portainer-ee
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy
      - portainer
    volumes:
      - portainer_data:/data

networks:
  proxy:
    external: true
  portainer:
    external: true

volumes:
  portainer_data:
