services:
  traefik:
    image: "traefik"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #- "./traefik.yml:/etc/traefik/traefik.yml" # TODO replace this and get rid of command
      - "./dynamic:/etc/traefik/dynamic"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      # - "--log.level=DEBUG"
      # - "--providers.swarm=true"
      - "--providers.file.directory=/etc/traefik/dynamic"

  whoami:
    image: "traefik/whoami"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
