---
- name: check if docker is installed
  tags:
    - docker_install
  ansible.builtin.command: docker --version
  register: docker_check

- name: clean docker before installation
  tags:
    - docker_install
  include_role:
    name: container/docker/clean
  when: docker_check.rc != 0

- name: docker install
  tags: 
    - docker_install
  become: true
  ansible.builtin.script: install.sh
  when: docker_check.rc != 0

- name: create docker group
  tags: 
    - docker_install
  become: true
  ansible.builtin.group:
    name: docker
    state: present
  when: docker_check.rc != 0

- name: add user to docker group
  tags: 
    - docker_install
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: docker_check.rc != 0

- name: enabled docker service
  tags: 
    - docker_install
  become: true
  ansible.builtin.service:
    name: docker
    enabled: true
  when: docker_check.rc != 0

- name: enabled containerd service
  tags: 
    - docker_install
  become: true
  ansible.builtin.service:
    name: containerd
    enabled: true
  when: docker_check.rc != 0

- name: flush handlers to restart docker
  tags: 
    - docker_install
  meta: flush_handlers
  when: docker_check.rc != 0

- name: reset connection to refresh user groups
  tags: 
    - docker_install
  meta: reset_connection
