api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  ping:
    address: ":8082"

# log:
#   level: DEBUG

providers:
  # swarm:
  #   endpoint: "unix:///var/run/docker.sock"
  #   exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yml"

ping:
  entryPoint: "ping"
