---
# see https://docs.docker.com/network/packet-filtering-firewalls/#docker-and-ufw

- name: install UFW firewall
  tags:
    - firewall_ufw
  become: true
  ansible.builtin.apt:
    name:
      - ufw
    state: latest

- name: enable UFW
  tags:
    - firewall_ufw
  become: true
  community.general.ufw:
    state: enabled

- name: default deny incoming connections
  tags:
    - firewall_ufw
  become: true
  community.general.ufw:
    default: deny
    direction: incoming

- name: default allow outgoing connections
  tags:
    - firewall_ufw
  become: true
  community.general.ufw:
    default: allow
    direction: outgoing

- name: allow ssh
  tags:
    - firewall_ufw
  become: true
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
