---
- name: "{{ orchestrator }} pre deploy"
  tags:
    - services_setup
  include_role:
    name: "orchestrator/{{ orchestrator }}/pre-deploy"

- name: "setup {{ service_name }}"
  tags:
    - services_setup
  include_role:
    name: "services/{{ service_name }}/setup"
  loop: "{{ services.keys() }}"
  loop_control:
    loop_var: service_name

- name: "{{ orchestrator }} post deploy"
  tags:
    - services_setup
  include_role:
    name: "orchestrator/{{ orchestrator }}/post-deploy"
