---
- name: "{{ orchestrator }} pre deploy"
  tags:
    - services_setup
  include_role:
    name: "orchestrator/{{ orchestrator }}/pre-deploy"

- name: setup reverse proxy
  tags:
    - services_setup
  include_role:
    name: services/reverse-proxy/setup

- name: setup dns
  tags:
    - services_setup
  include_role:
    name: services/dns/setup

- name: setup monitoring
  tags:
    - services_setup
  include_role:
    name: services/monitoring/setup

- name: "{{ orchestrator }} post deploy"
  tags:
    - services_setup
  include_role:
    name: "orchestrator/{{ orchestrator }}/post-deploy"
