---
- name: create netdata stack directory
  tags:
    - services_monitoring_netdata
  become: true
  ansible.builtin.file:
    path: /opt/stacks/netdata
    state: directory

- name: copy netdata compose file
  tags:
    - services_monitoring_netdata
  become: true
  ansible.builtin.copy:
    src: docker-compose/docker-compose.yaml
    dest: /opt/stacks/netdata/docker-compose.yaml

- name: deploy netdata stack
  tags:
    - services_monitoring_netdata
  community.docker.docker_stack:
    state: present
    name: monitoring
    prune: true
    compose:
      - /opt/stacks/netdata/docker-compose.yaml
