services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    deploy:
      replicas: 2
      mode: replicated
    environment:
      GROUP_ID: ${GROUP_ID}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      TASK_NAME: '{{ .Task.Name }}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-data:/etc/gitlab-runner
      - ./config/runner.sh:/opt/runner.sh
    entrypoint: ["/bin/sh", "/opt/runner.sh"]

volumes:
  gitlab-runner-data:
    driver: local
