server_nodes:
  hosts:
    server1.dev.home.local:
      ansible_host: 192.168.56.21
      storage: /mnt/external_hdd
      storage_mount: /mnt/storage
  vars:
    ansible_user: paulo
    orchestrator: docker-swarm
    services:
      reverse_proxy: traefik
      dns: coredns
