server_nodes:
  hosts:
    server1.dev.home.local:
      ansible_host: 192.168.1.21
      storage: /mnt/external_hdd
      storage_mount: /mnt/storage
  vars:
    ansible_user: paulo
    base_url: dev.home.local
    orchestrator: docker-swarm
    services:
      reverse_proxy: traefik
      dns: coredns
