---
- name: create gitlab stack directory
  tags:
    - services_vcs_gitlab
  ansible.builtin.file:
    path: /opt/stacks/gitlab
    state: directory

- name: copy gitlab compose file
  tags:
    - services_vcs_gitlab
  ansible.builtin.copy:
    src: docker-compose/docker-compose.yaml
    dest: /opt/stacks/gitlab/docker-compose.yaml

- name: include secrets.yaml
  tags:
    - services_vcs_gitlab
  ansible.builtin.include_vars:
    file: secrets.yaml

- name: create docker secrets
  tags:
    - services_vcs_gitlab
  community.general.docker_secret:
    name: "{{ secret.key }}"
    data: "{{ secret.value }}"
    state: present
  with_dict: "{{ secrets }}"
  loop_control:
    loop_var: secret
  no_log: true

- name: copy gitlab config directory
  tags:
    - services_vcs_gitlab
  ansible.builtin.copy:
    src: config
    dest: /opt/stacks/gitlab

- name: deploy gitlab stack
  tags:
    - services_vcs_gitlab
  community.docker.docker_stack:
    state: present
    name: vcs
    prune: true
    compose:
      - /opt/stacks/gitlab/docker-compose.yaml
