---
- name: setup server
  hosts: server_nodes
  roles:
    - system/upgrade
    - system/hostname
    - system/ssh
    # - system/swap # TODO make it work
    - firewall/setup
    - container/setup
    - orchestrator/setup
    - services/setup
