---
- name: create coredns stack directory
  tags:
    - services_dns_coredns
  ansible.builtin.file:
    path: /opt/stacks/coredns
    state: directory

- name: copy coredns compose file
  tags:
    - services_dns_coredns
  ansible.builtin.copy:
    src: docker-compose/docker-compose.yaml
    dest: /opt/stacks/coredns/docker-compose.yaml

- name: copy coredns Corefile
  tags:
    - services_dns_coredns
  ansible.builtin.template:
    src: config/Corefile.j2
    dest: /opt/stacks/coredns/Corefile

- name: deploy coredns stack
  tags:
    - services_dns_coredns
  community.docker.docker_stack:
    state: present
    name: dns
    prune: true
    compose:
      - /opt/stacks/coredns/docker-compose.yaml
