---
- name: create cadvisor stack directory
  tags:
    - services_monitoring_cadvisor
  become: true
  ansible.builtin.file:
    path: /opt/stacks/cadvisor
    state: directory

- name: copy cadvisor compose file
  tags:
    - services_monitoring_cadvisor
  become: true
  ansible.builtin.copy:
    src: docker-compose/docker-compose.yaml
    dest: /opt/stacks/cadvisor/docker-compose.yaml

- name: deploy cadvisor stack
  tags:
    - services_monitoring_cadvisor
  community.docker.docker_stack:
    state: present
    name: monitoring
    prune: true
    compose:
      - /opt/stacks/cadvisor/docker-compose.yaml
